# SonarQube server settings
sonar.host.url=http://localhost:9000
sonar.token=squ_0fd4536851cf9ce68f245706a06069922b8a0853

# Project identification
sonar.projectKey=econ
sonar.projectName=econ
sonar.projectVersion=1.0

# Analysis settings
# Analyze client and backend source code
sonar.sources=client,config,controllers,helpers,middlewares,models

sonar.language=js
sonar.inclusions=**/*.js
sonar.exclusions=**/*.test.js,**/*.integration.test.js,**/*.test.js,**/*.spec.ts,client/src/setupTests.js,client/src/reportWebVitals.js,client/src/tests/helpers/**

# Import coverage for both backend and frontend
sonar.javascript.lcov.reportPaths=coverage/backend/lcov.info,coverage/frontend/lcov.info
